export enum ScreenNames {
  WITH_BOTTOMTABS = 'WITH_BOTTOMTABS',
  CHAT = 'CHAT',
  MOMENTS = 'MOMENTS',
  MY_PROFILE = 'MY_PROFILE',
  GROUP_MEETING_STACK = 'GROUP_MEETING_STACK',
  GROUP_MEETING = 'GROUP_MEETING',
  GROUP_MEETING_DETIAL = 'GROUP_MEETING_DETIAL',
}
