export enum ScreenNames {
  WITH_BOTTOM_TABS = 'WITH_BOTTOM_TABS',
  CHAT = 'CHAT',
  MOMENTS = 'MOMENTS',
  MY_PROFILE = 'MY_PROFILE',
  GROUP_MEETING_STACK = 'GROUP_MEETING_STACK',
  GROUP_MEETING = 'GROUP_MEETING',
  GROUP_MEETING_DETAIL = 'GROUP_MEETING_DETAIL',
  GROUP_MEETING_EVENT_DETAIL = 'GROUP_MEETING_EVENT_DETAIL',
}
